name: Build runner

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Build
        run: cd runner && go build . && mv studio-runner runner

      - uses: actions/upload-artifact@v3
        with:
          name: runner
          path: ./runner/runner
