name: Build server

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Build
        run: cd server && go build . && mv studio server

      - uses: actions/upload-artifact@v3
        with:
          name: server
          path: ./server/server

      - name: Upload binary to server
        uses: Creepios/sftp-action@v1.0.3
        with:
          host: "${{ secrets.SSH_HOST }}"
          port: 22
          username: "${{ secrets.SSH_USER }}"
          password: "${{ secrets.SSH_PASSWORD }}"
          localPath: "./server/server"
          remotePath: "./antin0de-studio/"
